# # .github/workflows/deploy.yml

# name: 'Terraform Main Deploy to Azure'

# on:
# #   push:
# #     branches:
# #       - main
# #   pull_request:
# #     branches:
# #       - main
#   workflow_dispatch:

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         terraform_version: 1.1.6

#     - name: Azure Login via Service Principal
#       env:
#         ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
#         ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
#         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
#       run: |
#         echo "Logging in via Azure Service Principal"
#         az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

#     - name: Terraform Init
#       run: terraform init
#       working-directory: ./terraform

#     - name: Terraform Plan
#       run: terraform plan -var-file="var.tfvars"
#       working-directory: ./terraform

#     - name: Terraform Apply
#       if: github.ref == 'refs/heads/main'  # Only apply on main branch
#       run: terraform apply -var-file="var.tfvars" -auto-approve
#       working-directory: ./terraform



# .github/workflows/deploy.yml

name: 'Terraform Main Deploy to Azure'

on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Terraform Init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        terraform init \
          -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      working-directory: ./terraform
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Terraform Plan
      run: terraform plan -var-file="var.tfvars"
      working-directory: ./terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'  # Only apply on main branch
      run: terraform apply -var-file="var.tfvars" -auto-approve
      working-directory: ./terraform
